name: Kwiki-Search-Spotlight
version: 0.01
abstract: Use Spotlight as Kwiki search engine
author: Kang-min Liu <gugod@gugod.org>
license: perl
distribution_type: module
build_requires:
  Test::More: 0
  File::Which: 0
requires:
  Kwiki: 0.38
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.36
